language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"


deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID  #Se debe de cambiar 
  secret_access_key:
    secure: "$SECRETACCESSKEY"  #Se debe de cambiar 
  region: "ca-central-1"    #Se debe de cambiar 
  app: "elastic-beanstalk-tutorial"  #Se debe de cambiar 
  env: "elastic-beanstalk-tutorial-dev"  #Se debe de cambiar 
  bucket_name: "elasticbeanstalk-ca-central-1-882371129764" #Se debe de cambiar 
  on:
    branch: master
